export const SET_AUTH = "SET_AUTH"
export const SET_SITE_TYPE = "SET_SITE_TYPE"
export const SET_EXPLORE_TYPE = "SET_EXPLORE_TYPE"
export const SET_GENDER = "SET_GENDER"
export const SET_PERIOD = "SET_PERIOD"
